build-and-deploy:
    image: $CI_DOCS_DOCKER_IMAGE
    tags:
        - docs
    variables:
        GIT_SUBMODULE_STRATEGY: normal
        DOCS_DIR: 'doc'
    before_script:
        - pip3 install -r $DOCS_DIR/requirements.txt
    script:
        - cd $DOCS_DIR
        - make html latexpdf
        - cp build/latex/*.pdf build/html/
        - tar cf ../$CI_DOCS_ARCHIVE -C build/html/ .
    artifacts:
        paths:
            - $DOCS_DIR/build/
            - $CI_DOCS_ARCHIVE
