stages:
  - verify
  - pre-build
  - build-docs
  - deploy
  - build
  - test
  - test-upstream

variables:
  GIT_SUBMODULE_STRATEGY: none
  YAML_SOURCE_COMMIT: 12f4e6a83f1f81217662033b279eb457cbf904e5

include:
    - project: 'rowhammer-tester-ci'
      ref: 12f4e6a83f1f81217662033b279eb457cbf904e5
      file: '/ci-setup.yaml'
    - project: 'rowhammer-tester-ci'
      ref: 12f4e6a83f1f81217662033b279eb457cbf904e5
      file: '/ci-bitstream-setup.yaml'
    - project: 'rowhammer-tester-ci'
      ref: 12f4e6a83f1f81217662033b279eb457cbf904e5
      file: '/ci-hw-setup.yaml'
    - project: 'rowhammer-tester-ci'
      ref: 12f4e6a83f1f81217662033b279eb457cbf904e5
      file: '/pre-build-lint-and-unit-tests.yaml'
    - project: 'rowhammer-tester-ci'
      ref: 12f4e6a83f1f81217662033b279eb457cbf904e5
      file: '/build-docs.yaml'
    - project: 'rowhammer-tester-ci'
      ref: 12f4e6a83f1f81217662033b279eb457cbf904e5
      file: '/deploy-docs.yaml'
    - project: 'rowhammer-tester-ci'
      ref: 12f4e6a83f1f81217662033b279eb457cbf904e5
      file: '/build-ddr5-tester-linux.yaml'
    - project: 'rowhammer-tester-ci'
      ref: 12f4e6a83f1f81217662033b279eb457cbf904e5
      file: '/build-spds.yaml'
    - project: 'rowhammer-tester-ci'
      ref: 12f4e6a83f1f81217662033b279eb457cbf904e5
      file: '/build-bitstreams.yaml'
    - project: 'rowhammer-tester-ci'
      ref: 12f4e6a83f1f81217662033b279eb457cbf904e5
      file: '/tests-platforms.yaml'
    - project: 'rowhammer-tester-ci'
      ref: 12f4e6a83f1f81217662033b279eb457cbf904e5
      file: '/tests-sim.yaml'
    - project: 'rowhammer-tester-ci'
      ref: 12f4e6a83f1f81217662033b279eb457cbf904e5
      file: '/test-upstream-is-up-to-date.yaml'
