# payload_ddr4.proto.Payload
timing: {
  tick_ps: 1000
  ras: 32
  rp: 12
  rfc: 243
  rcd: 12
  ccd_l: 5
  ccd_s: 4
  rtp: 8
  rrd_l: 6
  rrd_s: 5
  faw: 28
}
instr: {
  mem: {
    opcode: ACT
    timeslice: 12
    bank_group: 2
    bank: 1
    addr: 8192
  }
}
instr: {
  mem: {
   opcode: RD
    timeslice: 5
    bank_group: 2
    bank: 1
    addr: 0
  }
}
instr: {
  mem: {
   opcode: RD
    timeslice: 5
    bank_group: 2
    bank: 1
    addr: 8
  }
}
instr: {
  mem: {
   opcode: RD
    timeslice: 5
    bank_group: 2
    bank: 1
    addr: 16
  }
}
instr: {
  mem: {
   opcode: RD
    timeslice: 5
    bank_group: 2
    bank: 1
    addr: 24
  }
}
