name: Rowhammer tester docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docs-generation:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - uses: docker://btdi/sphinx:min
        with:
          args: ./.github/scripts/sphinx.sh

      - uses: docker://btdi/latex
        with:
          args: ./.github/scripts/latex.sh

      - name: 'Upload artifact: Sphinx HTML and PDF'
        uses: actions/upload-artifact@v3
        with:
          name: Documentation
          path: docs/build/html

      - name: Deploy to Github Pages
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: |
          sudo chown -R $(whoami) docs
          cd docs/build/html
          touch .nojekyll
          git init
          cp ../../../.git/config ./.git/config
          git add .
          git config --local user.email "push@gha"
          git config --local user.name "GHA"
          git commit -am "update ${{ github.sha }}"
          git push -u origin +HEAD:gh-pages
          rm -rf .git
